### PR TITLE
Add Simulated Annealing Algorithm

### PR DESCRIPTION
**Pull request by Glitchy-Tozier**
See #3 for discussion.

This pull request is an attempt to add the [simulated annealing algorithm](https://en.wikipedia.org/wiki/Simulated_annealing) to this project. According to my current understanding, it may be the most productive algorithm for this kind of problem.

### CODE REVIEW

**Comment by Glitchy-Tozier** [comment]
@dariogoetz When you have time, could you aid me in the required traits to those three?
```rust
current_layout: Layout,
evaluator: Arc<Evaluator>,
layout_generator: PermutationLayoutGenerator,
```
turns out that (at least to someone with limited Rust-experience) some of this stuff is really complicated.

**Comment by dariogoetz** [comment]
I had a look at the code and I have some questions:
1. Is there a reason, why you use an old version of the `argmin` crate (you use 0.2.4, current is 0.4.4)?
2. If I understand the `ArgminOp` trait correctly, not the `SomeStruct` struct in your code needs to implement the De-/Serialize trait, but the `type` fields in the `ArgminOp` trait, most notably `Param`, which is `Layout` in your case. The `Layout` struct, however, is mostly used internally, so I would try to avoid implementing the De-/Serialize traits for it (though it should be possible).
I would suggest using either the String representation for `Param` (e.g. `zluaqj.dmy,ßcrieobntsgvxüäöphwfk` as provided by the `Layout`'s `as_text()` method) or even use an more abstract representation as permutation indices `Vec<usize>` as for the `genevo` implementation. There it was necessary because the `genevo` crate required it to be of such form.
The `PermutationLayoutGenerator` struct in `common.rs` is made for using such `Vec<usize>` representations.
This would give the following:
```rust
impl ArgminOp for SomeStruct {
    type Param = Vec<usize>;
    type Output = f64;
    type Hessian = ();
    type Jacobian = ();
    type Float = f64;
    ...
```
Note, that `type Float=f64;` is required.
3. You do not need a `current_layout` in the `SomeStruct`. The "current layout" is provided as `param` in the `apply` function of the `ArgminOp` trait.

**Comment by Glitchy-Tozier** [comment]
> 1. Is there a reason, why you use an old version of the argmin crate (you use 0.2.4, current is 0.4.4)?

No, I either mistyped or was shown an outdated version of the crate when I first started.

> I would suggest using either the String representation for Param (e.g. zluaqj.dmy,ßcrieobntsgvxüäöphwfk as provided by the Layout's as_text() method) or even use an more abstract representation as permutation indices Vec<usize> as for the genevo implementation.

Do you think there would be a speed-difference, depending on which representation we use?

> 3. You do not need a current_layout in the SomeStruct. The "current layout" is provided as param in the apply function of the ArgminOp trait.

Thank you for pointing that out, I'm still in the process of figuring out what exactly I have to do.

**Comment by dariogoetz** [comment]
No, the speed difference would be negligible. The generation of a layout is several orders of magnitude faster than an evaluation.

As I said, my understanding is that neither of the structs that you mentioned need the `De-/Serialize` trait. I mean those ones:
```rust
current_layout: Layout,
evaluator: Arc<Evaluator>,
layout_generator: PermutationLayoutGenerator,
```
None of these require it. The requirement lies on `Param` in
```rust
impl ArgminOp for SomeStruct {
    type Param = Vec<usize>;
    type Output = f64;
```
So `Vec<usize>` is `De-/Serialize`. Alternatively, use `String` for `Param`, i.e.
```rust
impl ArgminOp for SomeStruct {
    type Param = String;
    type Output = f64;
```

**Comment by dariogoetz** [comment]
Example implementation:
```rust
impl ArgminOp for SomeStruct {
    type Param = Vec<usize>;
    type Output = f64;
    type Hessian = ();
    type Jacobian = ();
    type Float = f64;

    fn apply(&self, param: &Self::Param) -> Result<Self::Output, Error> {
        let layout = self.layout_generator.generate_layout(&param);
        let evaluation_result = self.evaluator.evaluate_layout(&layout);
        Ok(evaluation_result.optimization_score() as f64)
    }

    /// This function is called by the annealing function
    fn modify(&self, param: &Self::Param, temp: f64) -> Result<Self::Param, Error> {
        // in the following, the 1 will be replaced by something `temp`-depending
        Ok(self.layout_generator.switch_n_keys(&param, 1))
    }
}
```

Now the `switch_n_keys` would need to be slightly different:
```rust
    /// Takes in a Layout, switches [nr_switches] keys in that layout, then returns it.
    pub fn switch_n_keys(&self, permutation: &[usize], nr_switches: usize) -> Vec<usize> {
        let mut indices: Vec<usize> = permutation.to_vec();

        // shuffle some (self.n_switches) permutable chars
        indices.partial_shuffle(&mut thread_rng(), nr_switches);
        indices
    }
```

**Comment by dariogoetz** [comment]
The reason I did not choose `Vec<usize>` for the `abc` implementation is that I was bound to use its streaming implementation, which would send intermediate solutions to the "outside" (the calling code). Only a permutation can not be interpreted by the outside, because the `PermutationLayoutGenerator` is not available there. Hence, I needed to directly use a `String` representation, because this can be interpreted by the standard `NeoLayoutGenerator`.

**Comment by Glitchy-Tozier** [comment]
I'll do my best to implement your input, thank you :)

**Comment by dariogoetz** [comment]
Can the branch be merged?

**Comment by Glitchy-Tozier** [comment]
I guess so... It would be nice to know why (when not using `--greedy`), it goes to 99_000 iterations.
I won't have time to do some testing during the next few days, so if you want, we can merge!

**Pull request merged**
