### PR TITLE
Add `lock` modifier type

### LINKED ISSUE #59: Questions regarding keyboard-config: `modifiers`
1. Is there a way to simulate a Caps-lock for a layer?
Context: I'm thinking about optimizing a Georgian layout (you have seen the emails). It uses non-latin letters but has two layers that users can "caps-lock" to, where they can find latin letters ("abcdefg...").
Currently I'm not sure how to achieve optimization for caps-lock functionality. Could you help me with that?

2. The `modifiers`-option itself:
    1. It would be great to have some kind of explanation above the setting, explaining what it does, how it is determined which layers these modifiers switch to and what values can be used under `type`.
    2. `value` wants me to define which `MatrixPositions` need to be pressed down to activate that modifier, correct? It would be helpful to name that option something indicating what it does. I'm not sure what naming to suggest, however. The best idea I have is, again, `matrix_positions`, but I'm pretty sure we can think of something even more intuitive.
```yml
  modifiers:
    - Left:
        type: hold
        value: [[0,3]]
      Right:
        type: hold
        value: [[18,3]]
    - Left:
        type: hold
        value: [[0,2]]
      Right:
        type: hold
        value: [[18,2]]
    - Left:
        type: hold
        value: [[1,3]]
      Right:
        type: hold
        value: [[16,4]]
    - Left:
        type: hold
        value: [[0,3], [1,3]]
      Right:
        type: hold
        value: [[18,3], [16,4]]
    - Left:
        type: hold
        value: [[0,2], [1,3]]
      Right:
        type: hold
        value: [[18,2], [16,4]]
```

### PR DESCRIPTION
**Pull request by Glitchy-Tozier**
Closes #59.

Adds the `lock`-modifier variant to the optimizer, which acts the way CAPS-LOCK works.

ToDo:
- [x] Add all necessary functions
- [x] Test code
- [ ] After testing, remove print-statements

### CODE REVIEW

**Comment by Glitchy-Tozier** [comment]
1. If you have any feedback for `process_lock_layers()` in the `BigramMapper`, I'd be happy to hear it. I took a page out of how you wrote the `process_hold_modifiers()`-function.
1. Question: Doesn't `process_hold_layers()` radically transform ALL keys to their base-variants, regardless of what mod-type they're using?
If yes, I feel like we should adapt that function slightly, as `process_lock_layers()` still needs to come after it.

**Comment by Glitchy-Tozier** [comment]
@dariogoetz I've implemented all the necessary functions, and I'll slowly start testing now.

Could you do two things?
1. Look at the code and check if you find any logical flaws / clunky code that could be written faster or more elegantly?
2. The PR seems to get blocked by your test-branch, which seems to have been merged. Could you undo the last three commits so we can merge this PR once it's been properly tested?

**Comment by Glitchy-Tozier** [comment]
I have tested the functionality and it seems to work pretty well.
If you want to do some testing yourself, I could send you the files with quite a few `print`-statements added. This way you won't have to do too much writing.

**Comment by dariogoetz** [comment]
I hope to be able to find some time to look at the PR in a couple of weeks.

**Comment by dariogoetz** [comment]
Hi @Glitchy-Tozier. Sorry for taking so long to answer, life has been busy.

I have the feeling that adding the `Lock` modifier adds a lot of additional complexity to the (probably already too) complex code. With such lock-layers being used to type longer sections of text without changing layers, I guess that the effect of the layer activation will not be very strong in the evaluation and therefore the feature does not really justify the additional complexity.

There are, however, multiple other nice fixes and improvements in the pull request that I tried cherry-picking as far as possible.

**Comment by Glitchy-Tozier** [comment]
Well that's unfortunate. I'm glad at least some commits could help improve the project.

**Pull request closed without merging**
